export const cities = [
  { value: 1, title: "New York" },
  { value: 2, title: "Los Angeles" },
  { value: 3, title: "Chicago" },
  { value: 4, title: "Houston" },
  { value: 5, title: "Phoenix" },
  { value: 501, title: "A person who, as a suspected or confirmed juvenile, has been required to leave and has left, or been removed from, licensed premises or regulated premises and remains on any footpath or in any area subject to the control or management of the licensee" },
  { value: 6, title: "Philadelphia" },
  { value: 101, title: "Another longer chip that is too long to show fully 1" },
  { value: 103, title: "Another longer value" },
  { value: 7, title: "San Antonio" },
  { value: 102, title: "Another longer chip that is too long to show fully 2" },
  { value: 8, title: "San Diego" },
  { value: 9, title: "Dallas" },
  { value: 10, title: "San Jose" },
  { value: 11, title: "Austin" },
  { value: 12, title: "Jacksonville" },
  { value: 13, title: "Fort Worth" },
  { value: 14, title: "Columbus" },
  { value: 15, title: "Charlotte" },
  { value: 16, title: "San Francisco" },
  { value: 17, title: "Indianapolis" },
  { value: 18, title: "Seattle" },
  { value: 19, title: "Denver" },
  { value: 20, title: "Washington" },
  { value: 21, title: "Boston" },
  { value: 22, title: "El Paso" },
  { value: 23, title: "Nashville" },
  { value: 24, title: "Detroit" },
  { value: 25, title: "Oklahoma City" },
  { value: 26, title: "Portland" },
  { value: 27, title: "Las Vegas" },
  { value: 28, title: "Memphis" },
  { value: 29, title: "Louisville" },
  { value: 30, title: "Baltimore" },
  { value: 31, title: "Milwaukee" },
  { value: 32, title: "Albuquerque" },
  { value: 33, title: "Tucson" },
  { value: 34, title: "Fresno" },
  { value: 35, title: "Sacramento" },
  { value: 36, title: "Mesa" },
  { value: 37, title: "Kansas City" },
  { value: 38, title: "Atlanta" },
  { value: 39, title: "Omaha" },
  { value: 40, title: "Raleigh" },
  { value: 41, title: "Miami" },
  { value: 42, title: "Long Beach" },
  { value: 43, title: "Virginia Beach" },
  { value: 44, title: "Oakland" },
  { value: 45, title: "Minneapolis" },
  { value: 46, title: "Tulsa" },
  { value: 47, title: "Arlington" },
  { value: 48, title: "Tampa" },
  { value: 49, title: "New Orleans" },
  { value: 50, title: "Wichita" },
  { value: 51, title: "Cleveland" },
  { value: 52, title: "Bakersfield" },
  { value: 53, title: "Aurora" },
  { value: 54, title: "Anaheim" },
  { value: 55, title: "Honolulu" },
  { value: 56, title: "Santa Ana" },
  { value: 57, title: "Riverside" },
  { value: 58, title: "Corpus Christi" },
  { value: 59, title: "Lexington" },
  { value: 60, title: "Henderson" },
  { value: 61, title: "Stockton" },
  { value: 62, title: "Saint Paul" },
  { value: 63, title: "Cincinnati" },
  { value: 64, title: "St. Louis" },
  { value: 65, title: "Pittsburgh" },
  { value: 66, title: "Greensboro" },
  { value: 67, title: "Lincoln" },
  { value: 68, title: "Anchorage" },
  { value: 69, title: "Plano" },
  { value: 70, title: "Orlando" },
  { value: 71, title: "Irvine" },
  { value: 72, title: "Newark" },
  { value: 73, title: "Durham" },
  { value: 74, title: "Chula Vista" },
  { value: 75, title: "Toledo" },
  { value: 76, title: "Fort Wayne" },
  { value: 77, title: "St. Petersburg" },
  { value: 78, title: "Laredo" },
  { value: 79, title: "Jersey City" },
  { value: 80, title: "Chandler" },
  { value: 81, title: "Madison" },
  { value: 82, title: "Lubbock" },
  { value: 83, title: "Scottsdale" },
  { value: 84, title: "Reno" },
  { value: 85, title: "Buffalo" },
  { value: 86, title: "Gilbert" },
  { value: 87, title: "Glendale" },
  { value: 88, title: "North Las Vegas" },
  { value: 89, title: "Winston-Salem" },
  { value: 90, title: "Chesapeake" },
  { value: 91, title: "Norfolk" },
  { value: 92, title: "Fremont" },
  { value: 93, title: "Garland" },
  { value: 94, title: "Irving" },
  { value: 95, title: "Hialeah" },
  { value: 96, title: "Richmond" },
  { value: 97, title: "Boise" },
  { value: 98, title: "Spokane" },
  { value: 99, title: "Baton Rouge" },
  { value: 100, title: "Tacoma" },
];
